### ISSUE TITLE
warning: module attribute @shortdoc was set but never used

### ISSUE THREAD

**Issue by stephanos** [awetzel/mailibex#22]
I'm using `mailibex` in my project and every day I see 

```
warning: module attribute @shortdoc was set but never used
  /.../project/deps/mailibex/mix.exs:2
```

multiple times and it's annoying (because I keep thinking I introduced it).

Would you be opposed to its removal?

**Comment by Shakadak** [comment]
Hi, I'll have a look at it

**Comment by Shakadak** [comment]
Will be published at a later date
